name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest] # [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Install Bevy dependencies
      run: sudo apt-get update; sudo apt-get install --no-install-recommends -yq libasound2-dev libudev-dev;
      if: runner.os == 'linux'
    - name: install RFD dependencies
      run: sudo apt-get update; sudo apt-get install -yq libgtk-3-dev
      if: runner.os == 'linux'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
